### PR TITLE
Update to include a README file

### PR DESCRIPTION
**Pull request by lukecav**
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes

### CODE REVIEW

**Comment by svenba** [comment]
This GIT repository is linked to the SVN repository of WordPress and has already a readme (SVN default format).

**Comment by lukecav** [comment]
README.md is lot more readable on GitHub though. There must be a way to exclude that specific file when it is pushed to SVN.

**Comment by lukecav** [comment]
https://stackoverflow.com/questions/17298668/svn-ignore-like-gitignore

**Comment by svenba** [comment]
Sure it is possible to ignore it in SVN. However, having a duplicate README is not something that we want. Let's keep this repository clean and lean, thanks.

**Comment by lukecav** [comment]
Two examples of GitHub repos that do have the correct README.md file present.

https://github.com/woocommerce/woocommerce/blob/master/README.md
https://github.com/Yoast/wordpress-seo/blob/trunk/README.md

**Comment by svenba** [comment]
We're going to add a README.md soon.

**Pull request closed without merging**
